server:
  port: 9999

logging.level.org.springframework:
  hibernate: debug
  oauth2: debug
  security: debug
  web: debug

spring:
  jpa:show-sql: true
  web:log-request-details: true

  profiles:
    active: develop

  security:
    user:
      name: user
      password: user123
      roles: USER

  data:
    mongodb:
      host: 172.21.0.3
      port: 27017
      database: youtube-mongodb
      authentication-database: root
      username: user1
      password: user1
      uri: mongodb://user1:user1@172.20.0.3:27017/youtube-mongodb

clients:
  youtube:
    baseUrl: https://www.googleapis.com/youtube/v3/playlistItems?
    maxResults: 25
    key: ${YOUTUBE_API_KEY}